/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TendersRouteImport } from './routes/tenders'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TendersIndexRouteImport } from './routes/tenders.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TendersTenderIdRouteImport } from './routes/tenders.$tenderId'
import { Route as AdminPublishRouteImport } from './routes/admin.publish'
import { Route as TendersTenderIdBidRouteImport } from './routes/tenders.$tenderId.bid'
import { Route as TendersTenderIdAuditRouteImport } from './routes/tenders.$tenderId.audit'

const TendersRoute = TendersRouteImport.update({
  id: '/tenders',
  path: '/tenders',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TendersIndexRoute = TendersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TendersRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TendersTenderIdRoute = TendersTenderIdRouteImport.update({
  id: '/$tenderId',
  path: '/$tenderId',
  getParentRoute: () => TendersRoute,
} as any)
const AdminPublishRoute = AdminPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => AdminRoute,
} as any)
const TendersTenderIdBidRoute = TendersTenderIdBidRouteImport.update({
  id: '/bid',
  path: '/bid',
  getParentRoute: () => TendersTenderIdRoute,
} as any)
const TendersTenderIdAuditRoute = TendersTenderIdAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => TendersTenderIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/company': typeof CompanyRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tenders': typeof TendersRouteWithChildren
  '/admin/publish': typeof AdminPublishRoute
  '/tenders/$tenderId': typeof TendersTenderIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/tenders/': typeof TendersIndexRoute
  '/tenders/$tenderId/audit': typeof TendersTenderIdAuditRoute
  '/tenders/$tenderId/bid': typeof TendersTenderIdBidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/company': typeof CompanyRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/publish': typeof AdminPublishRoute
  '/tenders/$tenderId': typeof TendersTenderIdRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/tenders': typeof TendersIndexRoute
  '/tenders/$tenderId/audit': typeof TendersTenderIdAuditRoute
  '/tenders/$tenderId/bid': typeof TendersTenderIdBidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/company': typeof CompanyRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tenders': typeof TendersRouteWithChildren
  '/admin/publish': typeof AdminPublishRoute
  '/tenders/$tenderId': typeof TendersTenderIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/tenders/': typeof TendersIndexRoute
  '/tenders/$tenderId/audit': typeof TendersTenderIdAuditRoute
  '/tenders/$tenderId/bid': typeof TendersTenderIdBidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/company'
    | '/docs'
    | '/features'
    | '/how-it-works'
    | '/sitemap.xml'
    | '/tenders'
    | '/admin/publish'
    | '/tenders/$tenderId'
    | '/admin/'
    | '/tenders/'
    | '/tenders/$tenderId/audit'
    | '/tenders/$tenderId/bid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/company'
    | '/docs'
    | '/features'
    | '/how-it-works'
    | '/sitemap.xml'
    | '/admin/publish'
    | '/tenders/$tenderId'
    | '/admin'
    | '/tenders'
    | '/tenders/$tenderId/audit'
    | '/tenders/$tenderId/bid'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/company'
    | '/docs'
    | '/features'
    | '/how-it-works'
    | '/sitemap.xml'
    | '/tenders'
    | '/admin/publish'
    | '/tenders/$tenderId'
    | '/admin/'
    | '/tenders/'
    | '/tenders/$tenderId/audit'
    | '/tenders/$tenderId/bid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CompanyRoute: typeof CompanyRoute
  DocsRoute: typeof DocsRoute
  FeaturesRoute: typeof FeaturesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TendersRoute: typeof TendersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenders': {
      id: '/tenders'
      path: '/tenders'
      fullPath: '/tenders'
      preLoaderRoute: typeof TendersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenders/': {
      id: '/tenders/'
      path: '/'
      fullPath: '/tenders/'
      preLoaderRoute: typeof TendersIndexRouteImport
      parentRoute: typeof TendersRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tenders/$tenderId': {
      id: '/tenders/$tenderId'
      path: '/$tenderId'
      fullPath: '/tenders/$tenderId'
      preLoaderRoute: typeof TendersTenderIdRouteImport
      parentRoute: typeof TendersRoute
    }
    '/admin/publish': {
      id: '/admin/publish'
      path: '/publish'
      fullPath: '/admin/publish'
      preLoaderRoute: typeof AdminPublishRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tenders/$tenderId/bid': {
      id: '/tenders/$tenderId/bid'
      path: '/bid'
      fullPath: '/tenders/$tenderId/bid'
      preLoaderRoute: typeof TendersTenderIdBidRouteImport
      parentRoute: typeof TendersTenderIdRoute
    }
    '/tenders/$tenderId/audit': {
      id: '/tenders/$tenderId/audit'
      path: '/audit'
      fullPath: '/tenders/$tenderId/audit'
      preLoaderRoute: typeof TendersTenderIdAuditRouteImport
      parentRoute: typeof TendersTenderIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminPublishRoute: typeof AdminPublishRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPublishRoute: AdminPublishRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TendersTenderIdRouteChildren {
  TendersTenderIdAuditRoute: typeof TendersTenderIdAuditRoute
  TendersTenderIdBidRoute: typeof TendersTenderIdBidRoute
}

const TendersTenderIdRouteChildren: TendersTenderIdRouteChildren = {
  TendersTenderIdAuditRoute: TendersTenderIdAuditRoute,
  TendersTenderIdBidRoute: TendersTenderIdBidRoute,
}

const TendersTenderIdRouteWithChildren = TendersTenderIdRoute._addFileChildren(
  TendersTenderIdRouteChildren,
)

interface TendersRouteChildren {
  TendersTenderIdRoute: typeof TendersTenderIdRouteWithChildren
  TendersIndexRoute: typeof TendersIndexRoute
}

const TendersRouteChildren: TendersRouteChildren = {
  TendersTenderIdRoute: TendersTenderIdRouteWithChildren,
  TendersIndexRoute: TendersIndexRoute,
}

const TendersRouteWithChildren =
  TendersRoute._addFileChildren(TendersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CompanyRoute: CompanyRoute,
  DocsRoute: DocsRoute,
  FeaturesRoute: FeaturesRoute,
  HowItWorksRoute: HowItWorksRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TendersRoute: TendersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
